### ISSUE TITLE
startup hanging?

### ISSUE THREAD

**Issue by hampsterx** [uber/cherami-server#17]
hi there, sorry noob question, go is not my cup of tea..

```
cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.9 | CQL spec 3.4.2 | Native protocol v4]

./scripts/cherami-setup-schema
```

Ran fine, can see it has created something in Cassandra. However.

```
CHERAMI_ENVIRONMENT=laptop CHERAMI_CONFIG_DIR=`pwd`/config CHERAMI_STORE=/tmp/store ./cherami-server start all
```

seems to just sit there, no output, no logs. what am I missing? :(

**Comment by aravindvs** [comment]
@hampsterx it is actually not hanging but rather the cherami-server has started and is listening for requests. You should be able to use the CLI now to create destinatons/cgs. By default, unfortunately we don't log msgs to stdout. @theuningxu is fixing this to make sure we log useful messages to stdout: https://github.com/uber/cherami-server/pull/14

It will be merged soon and after that you should see messages to stdout by default.

**Comment by hampsterx** [comment]
sorry my bad, i see there is logging config in config/base.I have modified that and now have a chatty server :)

I was also using localhost for the client but I see it's bound to eth0

I see this in the logs now tho:

```
ERRO[0000] RingPop GetHosts failed                       ctrlID=24c71286 deploymentName= err="Not enough hosts to serve the request" module=extentMon
```
I get this now from client

```
 ./cherami-cli --hostport=10.10.10.60:4922 create destination /test/cherami
tchannel error ErrCodeBadRequest: no handler for service "cherami-frontendhost_staging" and method "BFrontend::createDestination"
('export CHERAMI_SHOW_STACKS=1' to see stack traces)
```

At least it is talking now ;)

**Comment by aravindvs** [comment]
@hampsterx - sorry for the late response. A recent change in the CLI requires another flag to be passed in... we are fixing the README as part of https://github.com/uber/cherami-server/pull/14

Try: cherami-cli --env=prod --hostport=<blah> create destination <blah>

**Comment by hampsterx** [comment]
@aravindvs thanks, still having issue using master (I see you just merged)

running server with CHERAMI_ENVIRONMENT=local

I can see

```
INFO[0000] New Frontend                                  deploymentName= frntID=cae94015 serviceName=cherami-frontendhost
```

But from client

```
 ./cherami-cli --env=local --hostport=10.10.10.60:4922 create destination /test/cherami
tchannel error ErrCodeBadRequest: no handler for service "cherami-frontendhost_local" and method "BFrontend::createDestination"

```
Looks like server is not prefixing the env onto the service name which the client is expecting :(

PS minor tweak in the docs you now have:

```
./cherami-cli --env=prod --hostport=<localIP>:4922 create destination /test/cherami
```
Can --env=prod be changed to --env=local

**Comment by aravindvs** [comment]
@hampsterx the "--env" flag is used internally for service discovery and so CHERAMI_ENVIRONMENT and the --env flags are tangential and doesn't relate with each other...
* CHERAMI_ENVIRONMENT is used to parse the config/*.yaml files. For example, if you give CHERAMI_ENVIRONMENT=local and have a config/local.yaml, that config will be parsed first and then base.yaml will be parsed. You can imagine having "logging" level as "error" in base but "debug" in local.yaml for testing.
* "--env" in the CLI is used to change how cherami internally advertises to service discovery, so that in case you have multiple deployments within a DC you can distinguish between which ones to talk to. That is why it is looking for "cherami-frontendhost_local" when you typed "local" as the env. "prod" is used to indicate use cherami as is i.e, "cherami-frontendhost" (no code change). In a nutshell, --env=local will only work if you change code to advertise cherami-frontendhost as cherami-frontendhost_local

**Comment by hampsterx** [comment]
@aravindvs boom! It works :)

Thank you for the explanation!
